version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
    volumes:
      - ".:/usr/app"

  database:
    image: mongo